// packages/fastify-svelte/virtual/root.svelte
<script>
import { Router, Route } from 'svelte-navigator'
import DXRoute from '/dx:route.svelte'
import { isServer } from '/dx:core.js'

export let url = null
export let payload
</script>

<Router url="{url}">
  {#each payload.routes as { path, component }}
    <Route path="{path}" let:location>
      <DXRoute 
        path={path}
        location={location}
        payload={payload}
        component={component} />
    </Route>
  {/each}
</Router>

// packages/fastify-dx-react/virtual/root.jsx
import { Suspense } from 'react'
import { DXRoute } from '/dx:core.jsx'

export default function Root ({ url, routes, head, ctxHydration, routeMap }) {
  return (
    <Suspense>
      <Router location={url}>
        <Routes>{
          routes.map(({ path, component: Component }) =>
            <Route
              key={path}
              path={path}
              element={
                <DXRoute
                  head={head}
                  ctxHydration={ctxHydration}
                  ctx={routeMap[path]}>
                  <Component />
                </DXRoute>
              } />,
          )
        }</Routes>
      </Router>
    </Suspense>
  )
}
