// starters/react/client/pages/index.jsx
import { Link } from 'react-router-dom'

export function getMeta () {
  return {
    title: 'Welcome to Fastify DX!'
  }
}

export default function Index () {
  return (
    <>
      <img src="/assets/logo.svg" />
      <h1>Welcome to Fastify DX for React!</h1>
      <ul className="columns-2">
        <li><Link to="/using-data">/using-data</Link> demonstrates how to 
        leverage the <code>getData()</code> function 
        and <code>useRouteContext()</code> to retrieve server data for a route.</li>
        <li><Link to="/using-store">/using-store</Link> demonstrates how to 
        leverage the 
        automated <a href="https://github.com/pmndrs/valtio">Valtio</a> store 
        to retrieve server data for a route and maintain it in a global 
        state even after navigating to another route.</li>
        <li><Link to="/client-only">/client-only</Link> demonstrates how to set 
        up a route for rendering on the client only (disables SSR).</li>
        <li><Link to="/server-only">/server-only</Link> demonstrates how to set 
        up a route for rendering on the server only (sends no JavaScript).</li>
        <li><Link to="/streaming">/streaming</Link> demonstrates how to set 
        up a route for SSR in streaming mode.</li>
      </ul>
    </>
  )
}

// starters/vue/client/pages/index.vue
<template>
  <h1>Welcome to Fastify DX for Vue!</h1>
  <p><img :src="logo" /></p>
  <ul class="columns-2">
    <li><router-link to="/using-data">/using-data</router-link> demonstrates how to 
    leverage the <code>getData()</code> function 
    and <code>useRouteContext()</code> to retrieve server data for a route.</li>
    <li><router-link to="/using-store">/using-store</router-link> demonstrates how to 
    leverage the 
    automated <a href="https://github.com/pmndrs/valtio">Valtio</a> store 
    to retrieve server data for a route and maintain it in a global 
    state even after navigating to another route.</li>
    <li><router-link to="/using-auth">/using-auth</router-link> demonstrates how to 
    wrap a route in a custom layout component.</li>
    <li><router-link to="/client-only">/client-only</router-link> demonstrates how to set 
    up a route for rendering on the client only (disables SSR).</li>
    <li><router-link to="/server-only">/server-only</router-link> demonstrates how to set 
    up a route for rendering on the server only (sends no JavaScript).</li>
    <li><router-link to="/streaming">/streaming</router-link> demonstrates how to set 
    up a route for SSR in streaming mode.</li>
  </ul>
</template>

<script setup>
import logo from '/assets/logo.svg'
</script>

<script>
export function getMeta () {
  return {
    title: 'Welcome to Fastify DX!'
  }
}
</script>
