// starters/solid/client/pages/streaming.jsx
import { createResource } from 'solid-js'

export const streaming = true

export default function Streaming () {
  const [message] = createResource(() => afterSeconds({
  	message: 'Delayed by Resource API',
  	seconds: 5,
  }))	
	return (
		<Suspense fallback={<p>Waiting for content</p>}>
			<Message message={message()} />
		</Suspense>
	)
}

function Message (props) {
	return (
		<p>{props.message}</p>
	)
}

function afterSeconds ({ message, seconds }) {
	return new Promise((resolve) => {
    setTimeout(() => {
    	resolve(message)
    }, seconds * 1000)
  })
}

// starters/vue/client/pages/streaming.vue
<template>
	<Suspense>
		<Message />
		<template #fallback>
			<p>Waiting for content</p>
		</template>
	</Suspense>
</template>

<script>
export const streaming = true

export default {
	async setup () {
	  const message = await afterSeconds({
	  	message: 'Delayed by Suspense API',
	  	seconds: 5
	  })
		return { message }
	}
}

const delays = new Map()

function afterSeconds ({ message, seconds }) {
  return new Promise((resolve) => {
    setTimeout(() => {
    	resolve(message)
    }, seconds * 1000)
  })
}
</script>
