// starters/react/client/pages/using-auth.jsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { useRouteContext } from '/dx:router.jsx'

export const layout = 'auth'

export function getMeta () {
  return { title: 'Using Custom Layout' }
}

export default function Index (props) {
  const {snapshot, state, actions} = useRouteContext()
  const [input, setInput] = useState(null)
  const addItem = async (value) => {
    await actions.addTodoItem(state, value)
    input.value = ''
  }
  return (
    <>
      <h2>Todo List — Using Custom Layout</h2>
      <ul>{
        snapshot.todoList.map((item, i) => {
          return <li key={`item-${i}`}>{item}</li>
        })
      }</ul>
      <div>
        <input ref={setInput} />
        <button onClick={() => addItem(input.value)}>Add</button>
      </div>
      <p>
        <Link to="/">Go back to the index</Link>
      </p>
      <p>⁂</p>
      <p>This example is exactly the same as <Link to="/using-store">/using-store</Link>,
      except it's wrapped in a custom layout which blocks it until 
      <code>user.authenticated</code> is <code>true</code> in the global state.</p>
    </>
  )
}

// starters/vue/client/pages/using-auth.vue
<template>
  <h2>Todo List — Using Custom Layout</h2>
  <ul>
    <li 
      v-for="(item, i) in state.todoList"
      :key="`item-${i}`">
      {{ item }}
    </li>
  </ul>
  <div>
    <input v-model="inputValue" />
    <button @click="addItem">Add</button>
  </div>
  <p>
    <router-link to="/">Go back to the index</router-link>
  </p>
  <p>⁂</p>
  <p>This example is exactly the same as <router-link to="/using-store">/using-store</router-link>,
  except it's wrapped in a custom layout which blocks it until 
  <code>user.authenticated</code> is <code>true</code> in the global state.</p>
</template>

<script>
import { useRouteContext } from '/dx:core.js'

export const layout = 'auth'

export function getMeta () {
  return { title: 'Using Custom Layout' }
}

export default {
  setup () {
    const {snapshot, state, actions} = useRouteContext()
    const [input, setInput] = useState(null)
    const addItem = async (value) => {
      await actions.addTodoItem(state, value)
      input.value = ''
    }
    return { state, addItem }
  }
}
</script>
