// packages/universify-react/base/client.jsx
import React, { Suspense, Fragment } from 'react'
import { Helmet } from 'react-helmet'
import { BrowserRouter, Route, Switch } from 'react-router-dom'
import { StaticRouter } from 'react-router'
import routes from '@app/routes.js'

export function createApp (context) {
  return {
    App,
    routes,
    router: import.meta.env.SSR ? StaticRouter : BrowserRouter,
    context,
  }
}

function App (routes, props) {
  return (
    <>
      <Helmet>
        <title>fastify-vite-react examples</title>
        <style>{`
        #app {
          font-family: Avenir, Helvetica, Arial, sans-serif;
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
          color: #2c3e50;
          margin-top: 60px;
        }
        body {
          margin: 0px auto;
          width: 500px;
        }
        ul {
          margin: 0px;
          padding: 0px;
        }
        li {
          list-style-type: none;
          padding-left:  0px;
        }
        li span {
          margin-right: 0.5rem;
        }
        code {
          font-weight:  bold;
          font-size:  1rem;
          color: #555;
        }
        `}</style>
      </Helmet>
      <h1>Examples</h1>
      {import.meta.env.SSR
        ? <Fragment>
            <Switch>
              {routes.map(({ path, component: RouteComp }) => {
                return (
                  <Route key={path} path={path}>
                    <RouteComp {...props} />
                  </Route>
                )
              })}
            </Switch>
          </Fragment>
        : <Suspense fallback={<div/>}>
            <Switch>
              {routes.map(({ path, component: RouteComp }) => {
                return (
                  <Route key={path} path={path}>
                    <RouteComp {...props} />
                  </Route>
                )
              })}
            </Switch>
          </Suspense>
      }
    </>
  )
}

// packages/fastify-vite-solid/base/client.jsx
/* eslint-disable react/jsx-key */

// import { Suspense } from 'solid-js'
// import { Title, Style, MetaProvider } from 'solid-meta'
import { Router, Route, Routes } from 'solid-app-router'
import routes from '@app/routes.js'

export function createApp (context) {
  return {
    App,
    routes,
    router: Router,
    context,
  }
}

/* <Title>fastify-vite-solid examples</Title>
      <Style>{`
      #app {
        font-family: Avenir, Helvetica, Arial, sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        color: #2c3e50;
        margin-top: 60px;
      }
      body {
        margin: 0px auto;
        width: 500px;
      }
      ul {
        margin: 0px;
        padding: 0px;
      }
      li {
        list-style-type: none;
        padding-left:  0px;
      }
      li span {
        margin-right: 0.5rem;
      }
      code {
        font-weight:  bold;
        font-size:  1rem;
        color: #555;
      }
      `}</Style> */

// {routes.map(({ path, component: RouteComp }) => {
//   return <Route path={path} element={<RouteComp />} />
// })}

function App (props) {
  return (
    <>
      <h1>Examples</h1>
      <Routes>
        {props.routes.map(({ path, component: RouteComp }) => {
          return (
            <Route path={path} component={RouteComp} />
          )
        })}
      </Routes>
    </>
  )
}
