// starters/solid/client/layouts/auth.jsx
import { children } from 'solid-js'
import { useRouteContext } from '/dx:core.js'

export default function Auth (props) {
  const c = children(() => props.children)
  const { actions, state } = useRouteContext()
  const authenticate = () => actions.authenticate(state)
  return (
    <div class="contents">
      {state.user.authenticated
        ? c()
        : <Login onClick={() => authenticate()} /> }
    </div>
  )
}

function Login (props) {
  return (
    <>
      <p>This route needs authentication.</p>
      <button onClick={props.onClick}>
        Click this button to authenticate.
      </button>
    </>
  )
}

// starters/react-ts/client/layouts/auth.jsx
import { Suspense } from 'react'
import { useRouteContext } from '/dx:core.jsx'

export default function Auth ({ children }) {
  const { actions, state, snapshot } = useRouteContext()
  const authenticate = () => actions.authenticate(state)
  return (
    <Suspense>
      {snapshot.user.authenticated
        ? children
        : <Login onClick={() => authenticate()} /> }
    </Suspense>
  )
}

function Login ({ onClick }) {
  return (
    <>
      <p>This route needs authentication.</p>
      <button onClick={onClick}>
        Click this button to authenticate.
      </button>
    </>
  )
}
