// starters/vue-ts/client/layouts/auth.vue
<template>
  <div class="contents">
    <template v-if="!state.user.authenticated">
      <p>This route needs authentication.</p>
      <button @click="actions.authenticate(state)">
        Click this button to authenticate.
      </button>
    </template>
    <slot v-else></slot>
  </div>
</template>

<script setup>
import { useRouteContext } from '/dx:core.js'
const { actions, state } = useRouteContext()
</script>

// starters/svelte/client/layouts/auth.svelte
<script>
import { useRouteContext } from '/dx:core.js'
const { snapshot, actions, state } = useRouteContext()
</script>

<div class="contents">
  {#if !$snapshot.user.authenticated}
    <p>This route needs authentication.</p>
    <button on:click={() => actions.authenticate(state)}>
      Click this button to authenticate.
    </button>
  {:else}
  <slot />
  {/if}  
</div>
