// starters/vue-ts/client/pages/client-only.vue
<template>
	<p>This route is rendered on the client only!</p>
  <p>
    <router-link to="/">Go back to the index</router-link>
  </p>
  <p>⁂</p>
  <p>When this route is rendered on the server, no SSR takes place.</p>
  <p>See the output of <code>curl http://localhost:3000/client-only</code>.</p>
</template>

<script>
export const clientOnly = true

export function getMeta () { 
	return {
		title: 'Client Only Page'
	}
}
</script>

// starters/react-ts/client/pages/client-only.jsx
import { Link } from 'react-router-dom'

export const clientOnly = true

export function getMeta () { 
  return {
    title: 'Client Only Page'
  }
}

export default function ClientOnly () {
  return (
    <>
      <p>This route is rendered on the client only!</p>
      <p>
        <Link to="/">Go back to the index</Link>
      </p>
      <p>⁂</p>
      <p>When this route is rendered on the server, no SSR takes place.</p>
      <p>See the output of <code>curl http://localhost:3000/client-only</code>.</p>
    </>
  )
}
