// starters/solid/client/root.jsx
import 'uno.css'
import { createContext, useContext, createSignal, children } from 'solid-js'
import { isServer, Suspense } from 'solid-js/web'
import { Router, Routes, Route } from 'solid-app-router'
import DXRoute from '/dx:route.jsx'

export default function Root (props) {
  return (
    <Router url={props.url}>
      <Routes>{
        // eslint-disable-next-line solid/prefer-for
        props.payload.routes.map(route =>
          <Route path={route.path} element={
            <DXRoute 
              path={route.path}
              payload={props.payload}
              component={route.component} />
          } />
        )
      }</Routes>
    </Router>
  )
}

// starters/react-ts/client/root.tsx
import 'virtual:uno.css'
import { Suspense } from 'react'
import { Routes, Route } from 'react-router-dom'
import { Router, DXRoute } from '/dx:core.jsx'

export default function Root ({ url, routes, head, ctxHydration, routeMap }) {
  return (
    <Suspense>
      <Router location={url}>
        <Routes>{
          routes.map(({ path, component: Component }) =>
            <Route
              key={path}
              path={path}
              element={
                <DXRoute
                  head={head}
                  ctxHydration={ctxHydration}
                  ctx={routeMap[path]}>
                  <Component />
                </DXRoute>
              } />,
          )
        }</Routes>
      </Router>
    </Suspense>
  )
}
