// starters/svelte/client/root.svelte
<script>
import 'uno.css'
import { Router, Route } from 'svelte-routing'
import DXRoute from '/dx:route.svelte'

export let url = null
export let head
export let routes
export let routeMap
export let ctxHydration
</script>

<Router url="{url}">
  {#each routes as { path, component }}
    <Route path="{path}" let:location>
    	<DXRoute 
    	  location={location}
    		head={head}
    		ctx={routeMap[path]}
    		ctxHydration={ctxHydration}
    		component={component} />
    </Route>
  {/each}
</Router>

// starters/react-ts/client/root.tsx
import 'virtual:uno.css'
import { Suspense } from 'react'
import { Routes, Route } from 'react-router-dom'
import { Router, DXRoute } from '/dx:core.jsx'

export default function Root ({ url, routes, head, ctxHydration, routeMap }) {
  return (
    <Suspense>
      <Router location={url}>
        <Routes>{
          routes.map(({ path, component: Component }) =>
            <Route
              key={path}
              path={path}
              element={
                <DXRoute
                  head={head}
                  ctxHydration={ctxHydration}
                  ctx={routeMap[path]}>
                  <Component />
                </DXRoute>
              } />,
          )
        }</Routes>
      </Router>
    </Suspense>
  )
}
