// packages/fastify-dx-react/mount.js
import { createRoot, hydrateRoot } from 'react-dom/client'

export default async function mount (target, { create, routes }) {
  if (typeof target === 'string') {
    target = document.querySelector(target)
  }
  routes = await routes
  if (window.route.clientOnly) {
    createRoot(target).render(create(routes, window.route))
  } else {
    hydrateRoot(target, create(routes, window.route))
  }
}

// packages/fastify-dx-solid/virtual/mount.js
import Head from 'unihead/client'
import { hydrate } from 'solid-js/web'

import create from '/dx:create.jsx'
import routesPromise from '/dx:routes.js'

mount('main')

async function mount (target) {
  if (typeof target === 'string') {
    target = document.querySelector(target)
  }
  const context = await import('/dx:context.js')
  const ctxHydration = await extendContext(window.route, context)
  const head = new Head(window.route.head, window.document)
  const resolvedRoutes = await routesPromise
  const routeMap = Object.fromEntries(
    resolvedRoutes.map((route) => [route.path, route]),
  )
  const app = create({
    head,
    ctxHydration,
    routes: window.routes,
    routeMap,
  })
  if (ctxHydration.clientOnly) {
    render(app, target)
  } else {
    hydrate(app, target)
  }
}

async function extendContext (ctx, {
  // The route context initialization function
  default: setter,
  // We destructure state here just to discard it from extra
  state,
  // Other named exports from context.js
  ...extra
}) {
  Object.assign(ctx, extra)
  if (setter) {
    await setter(ctx)
  }
  return ctx
}
