// packages/fastify-dx-react/index.js
import React from 'react'
import devalue from 'devalue'
import { Readable, PassThrough } from 'node:stream'
import Head from 'unihead'
import { createHtmlTemplateFunction } from 'fastify-vite'
import { createStreamHtmlFunction } from './html.js'
import { onAllReady, onShellReady } from './stream.js'
import { renderToPipeableStream } from 'react-dom/server'

// Helper function to prepend and append chunks the body stream
async function * streamHtml (head, body, footer) {
  yield head
  // We first await on the stream being ready (onShellReady)
  // And then await on its AsyncIterator
  for await (const chunk of await body) {
    yield chunk
  }
  yield footer
}

class RouteContext {
  constructor (server, req, reply, route) {
    this.server = server
    this.req = req
    this.reply = reply
    this.head = {}
    this.data = route.data
    this.static = route.static
    this.streaming = this.static ? false : route.streaming
    this.clientOnly = route.clientOnly
    this.serverOnly = route.serverOnly
  }

  toJSON () {
    return {
      data: this.data,
      static: this.static,
      clientOnly: this.clientOnly,
    }
  }
}

export default {
  createHtmlFunction,
  createRenderFunction,
  createRouteHandler,
  createRoute,
}

// // The return value of this function gets registered as reply.html()
// export function createHtmlFunction (source, scope, config) {
//   const sendHtml = createStreamHtmlFunction(onAllReady, source, scope, config)
//   const streamHtml = createStreamHtmlFunction(onShellReady, source, scope, config)
//   return function html (payload) {
//     this.type('text/html')
//     if (payload.context.streaming) {
//       streamHtml(this, payload)
//     } else {
//       console.log('!')
//       sendHtml(this, payload)
//     }
//   }
// }


// The return value of this function gets registered as reply.html()
function createHtmlFunction (source, scope, config) {
  const [headSource, footer] = source.split('<!-- element -->')
  const headTemplate = createHtmlTemplateFunction(headSource)
  return function ({ stream, context }) {
    const head = headTemplate({
      hydration: `<script>window.route = ${devalue({ data: context.data })}</script>`,
    })
    this.type('text/html')
    const readable = Readable
      .from(streamHtml(head, stream, footer))
      // Errors from React SSR can be captured here
      .on('error', console.log)
    this.send(readable)
  }
}

// Helper function to get an AsyncIterable (via PassThrough)
// from the limited stream returned by renderToPipeableStream()
function toReadable (app) {
  const duplex = new PassThrough()
  return new Promise((resolve, reject) => {
    try {
      const pipeable = renderToPipeableStream(app, {
        onShellReady () {
          resolve(pipeable.pipe(duplex))
        },
        onShellError (error) {
          reject(error)
        },
      })
    } catch (error) {
      resolve(error)
    }
  })
}

export function createRenderFunction ({ create }) {
  // createApp is exported by client/index.js
  return function (req) {
    console.log('req.route.head', req.route.head)
    const head = new Head(req.route.head).render()
    req.route.data = { 
      todoList: [
        'Do laundry',
        'Respond to emails',
        'Write report',
      ]
    }
    console.log('req.route', req.route)
    return {
      context: req.route,
      head,
      stream: toReadable(create(req.route, req.url)),
    }
  }
}

export function createRouteHandler (client, scope, config) {
  return function (req, reply) {
    reply.html(reply.render(req))
  }
}

export function createRoute ({ handler, errorHandler, route }, scope, config) {
  if (route.getData) {
    // If getData is provided, register JSON endpoint for it
    scope.get(`/-/data${route.path}`, async (req, reply) => {
      reply.send(await route.getData())
    })
  }
  scope.get(route.path, {
    onRequest (req, reply, done) {
      req.route = new RouteContext(scope, req, reply, route)
      done()
    },
    // If getData is provided,
    // make sure it runs before the SSR route handler
    // ...route.getData && {
    //   async preHandler (req, reply) {
    //     req.route.data = await route.getData()
    //   },
    // },
    handler,
    errorHandler,
    ...route,
  })
}

// packages/fastify-dx-solid/index.js
// Used to send a readable stream to reply.send()
import { Readable, PassThrough } from 'stream'

// fastify-vite's minimal HTML templating function,
// which extracts interpolation variables from comments
// and returns a function with the generated code
import { createHtmlTemplateFunction } from 'fastify-vite'

// Used to safely serialize JavaScript into
// <script> tags, preventing a few types of attack
import devalue from 'devalue'

// Small SSR-ready library used to generate
// <title>, <meta> and <link> elements
import Head from 'unihead'

// Hydration script helper from Solid
import { generateHydrationScript } from 'solid-js/web'

// Helper to build a stream from multiple fragments
import { generateHtmlStream } from './server/stream.js'

// Holds the universal route context
import RouteContext from './server/context.js'

export default {
  prepareClient,
  createHtmlFunction,
  createRenderFunction,
  createRouteHandler,
  createRoute,
}

export async function prepareClient ({
  renderToStream,
  routes: routesPromise,
  context: contextPromise,
  ...others
}) {
  const context = await contextPromise
  const resolvedRoutes = await routesPromise
  return { renderToStream, context, routes: resolvedRoutes, ...others }
}

// The return value of this function gets registered as reply.html()
export function createHtmlFunction (source, scope, config) {
  // Templating functions for universal rendering (SSR+CSR)
  const [unHeadSource, unFooterSource] = source.split('<!-- element -->')
  const unHeadTemplate = createHtmlTemplateFunction(unHeadSource)
  const unFooterTemplate = createHtmlTemplateFunction(unFooterSource)
  // Templating functions for server-only rendering (SSR only)
  const [soHeadSource, soFooterSource] = source
    // Unsafe if dealing with user-input, but safe here
    // where we control the index.html source
    .replace(/<script[^>]+type="module"[^>]+>.*?<\/script>/g, '')
    .split('<!-- element -->')
  const soHeadTemplate = createHtmlTemplateFunction(soHeadSource)
  const soFooterTemplate = createHtmlTemplateFunction(soFooterSource)
  const hydrationScript = generateHydrationScript()
  // This function gets registered as reply.html()
  return function ({ routes, context, stream, body }) {
    // Decide which templating functions to use, with and without hydration
    const headTemplate = context.serverOnly ? soHeadTemplate : unHeadTemplate
    const footerTemplate = context.serverOnly ? soFooterTemplate : unFooterTemplate
    // Render page-level <head> elements
    const head = new Head(context.head).render()
    // Create readable stream with prepended and appended chunks
    const readable = Readable.from(generateHtmlStream({
      stream,
      body,
      head: headTemplate({ ...context, head, hydrationScript }),
      footer: () => footerTemplate({
        ...context,
        // Decide whether or not to include the hydration script
        ...!context.serverOnly && {
          hydration: (
            '<script>\n' +
            `window.route = ${devalue(context.toJSON())}\n` +
            `window.routes = ${devalue(routes.toJSON())}\n` +
            '</script>'
          ),
        },
      }),
    }))
    // Send out header and readable stream with full response
    this.type('text/html')
    this.send(readable)
  }
}

export async function createRenderFunction ({
  renderToStringAsync,
  renderToStream,
  routes,
  create,
}) {
  // Convenience-access routeMap
  const routeMap = Object.fromEntries(
    routes.toJSON().map(route => [route.path, route]),
  )
  return async function (req) {
    let stream = null
    let body = null
    if (!req.route.clientOnly) {
      // Creates main Solid component with all the SSR context it needs
      const app = create({
        url: req.url,
        payload: {
          routes,
          routeMap,
          serverRoute: req.route,
        },
      })
      if (req.route.streaming) {
        const duplex = new PassThrough()
        renderToStream(app).pipe(duplex)
        stream = duplex
      } else {
        body = await renderToStringAsync(app)
      }
    }
    // Perform SSR, i.e., turn app.instance into an HTML fragment
    // The SSR context data is passed along so it can be inlined for hydration
    return {
      routes,
      context: req.route,
      stream,
      body,
    }
  }
}

export function createRouteHandler (client, scope, config) {
  return async function (req, reply) {
    reply.html(await reply.render(req))
    return reply
  }
}

export function createRoute ({ client, handler, errorHandler, route }, scope, config) {
  const onRequest = async function onRequest (req, reply) {
    req.route = await RouteContext.create(
      scope,
      req,
      reply,
      route,
      client.context,
    )
  }
  if (route.getData) {
    // If getData is provided, register JSON endpoint for it
    scope.get(`/-/data${route.path}`, {
      onRequest,
      async handler (req, reply) {
        reply.send(await route.getData(req.route))
      },
    })
  }

  // See https://github.com/fastify/fastify-dx/blob/main/URMA.md
  const hasURMAHooks = Boolean(
    route.getData || route.getMeta || route.onEnter,
  )

  // Extend with route context initialization module
  RouteContext.extend(client.context)

  scope.get(route.path, {
    onRequest,
    // If either getData or onEnter are provided,
    // make sure they run before the SSR route handler
    ...hasURMAHooks && {
      async preHandler (req, reply) {
        try {
          if (route.getData) {
            req.route.data = await route.getData(req.route)
          }
          if (route.getMeta) {
            req.route.head = await route.getMeta(req.route)
          }
          if (route.onEnter) {
            if (!req.route.data) {
              req.route.data = {}
            }
            const result = await route.onEnter(req.route)
            Object.assign(req.route.data, result)
          }
        } catch (err) {
          if (config.dev) {
            console.error(err)
          }
          req.route.error = err
        }
      },
    },
    handler,
    errorHandler,
    ...route,
  })
}
