// packages/universify-solid/base/entry/client.jsx
import { Suspense, hydrate as hydrateSolid } from 'solid-js/web'
import { ContextProvider, hydrate } from 'fastify-vite-solid/client.mjs'
import { createApp } from '@app/client.jsx'

const { App, routes, router: Router } = createApp()

hydrate().then(async (hydration) => {
  const resolvedRoutes = await routes()
  hydrateSolid(
    <ContextProvider context={hydration}>
      <Router>
        <Suspense>
          <App routes={resolvedRoutes} />
        </Suspense>
      </Router>
    </ContextProvider>,
    document.getElementById('app'),
  )
})

// packages/fastify-vite-react/base/entry/client.jsx
import ReactDOM from 'react-dom'
import { ContextProvider, hydrate } from 'fastify-vite-react/client.mjs'
import { createApp } from '@app/client.jsx'

const { App, routes, router: Router } = createApp()

hydrate().then(async (hydration) => {
  const app = App(await routes())
  ReactDOM.hydrate(
    <Router>
      <ContextProvider context={hydration}>
        {app}
      </ContextProvider>
    </Router>,
    document.getElementById('app'),
  )
})
