// starters/svelte-ts/client/root.svelte
<script>
import 'uno.css'
import { proxy } from 'sveltio'
import { Router, Route } from 'svelte-routing'
import DXRoute from '/dx:route.svelte'
import { isServer } from '/dx:core.js'

export let url = null
export let payload

let state = isServer
  ? payload.serverRoute.state
  : proxy(payload.serverRoute.state)
</script>

<Router url="{url}">
  {#each payload.routes as { path, component }}
    <Route path="{path}" let:location>
      <DXRoute 
        path={path}
        location={location}
        state={state}
        payload={payload}
        component={component} />
    </Route>
  {/each}
</Router>

// starters/solid-ts/client/root.tsx
import 'uno.css'
import { createMutable } from 'solid-js/store'
import { Router, Routes, Route } from 'solid-app-router'
import DXRoute from '/dx:route.jsx'
import { isServer } from '/dx:core.js'
import { For, mergeProps } from 'solid-js'

export default function Root(props) {
  props = mergeProps(
    {
      state: isServer
        ? props.payload.serverRoute.state
        : createMutable(props.payload.serverRoute.state)
    },
    props
  )

  // This is so we can serialize state into the hydration payload after SSR is done
  return (
    <Router url={props.url}>
      <Routes>
        {
          <For each={props.payload.routes}>
            {(route) => (
              <Route
                path={route.path}
                element={
                  <DXRoute
                    state={props.payload.serverRoute.state}
                    path={route.path}
                    payload={props.payload}
                    component={route.component}
                  />
                }
              />
            )}
          </For>
        }
      </Routes>
    </Router>
  )
}
